project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /en/**/*.md
    translation: /%locale_with_underscore%/**/%file_name%.md
  - source: /.vitepress/config/en.ts
    translation: /.vitepress/config/%locale_with_underscore%.ts
